### ISSUE TITLE
Filter only filters the headers , it doesn't get the parameters from the request.

### ISSUE THREAD

**Issue by Aprajita-96** [techguy-bhushan/XssRequestFilters#2]
The CustomXssFilter you have used to intercept the request is only capturing the headers and not the parameters present in the request.

**Comment by techguy-bhushan** [comment]
Hi @Aprajita-96 , sorry for the late response just busy in other projects.
Parameters are already handled in the process.
CustomXssFilter use **CaptureRequestWrapper**  , which have methods **getParameterValues** , **getHeader** which are responsible for handling parameters as well as header request.

**Comment by techguy-bhushan** [comment]
@Aprajita-96 please let me know if you have any queries regarding it.
Thank you!

**Comment by Aprajita-96** [comment]
Yes @techguy-bhushan , Ideally that must capture the parameters because that extends HttpServletRequestWrapper which overrides methods to capture parameters but that doesn't work that way. I see the headers are filtered but the parameters aren't.

**Comment by techguy-bhushan** [comment]
@Aprajita-96 
I think you are testing data with json/xml, as currently this version only supports **form data** , 
json/xml is the next in  road map of XssRequestFilters, I will start working on it asap.

**Comment by Aprajita-96** [comment]
@techguy-bhushan - Yes i was testing with json payloads. Thanks for the information. Also, I did try implementing JsonSerializers to handle cases of dealing with JSON payloads. 

You can check my repository- https://github.com/Aprajita-96/XssAttacksRemediation

**Comment by techguy-bhushan** [comment]
@Aprajita-96 
You need to intercept the request and fetch JSON data using **request.getReader();** , then using json desacralized need to filter the json data.

**Comment by techguy-bhushan** [comment]
Added filter xss  support for json request.
