### ISSUE TITLE
Why is the custom annotation name is @XxsFilter instead of @XssFilter ？

### ISSUE THREAD

**Issue by renyuanwei** [techguy-bhushan/XssRequestFilters#3]
Why is the custom annotation name is @XxsFilter instead of @XssFilter ？Is it deliberately done?

**Comment by techguy-bhushan** [comment]
Hi @renyuanwei  I was not active from long time so unable to work on it. I start work on it again. I you suggest I have renamed XxsFilter to XssFilter and added support for filter xss in json request. Thank you for raise this issue.
