### ISSUE TITLE
Not able to start application

### ISSUE THREAD

**Issue by raouday79** [techguy-bhushan/XssRequestFilters#4]
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.xss.filters.config.XssFiltersConfiguration.xssMatches(XssFiltersConfiguration.java:44)

The following method did not exist:

    org.springframework.web.servlet.mvc.method.RequestMappingInfo.getPathPatternsCondition()Lorg/springframework/web/servlet/mvc/condition/PathPatternsRequestCondition;

The method's class, org.springframework.web.servlet.mvc.method.RequestMappingInfo, is available from the following locations:

    jar:file:/C:/Users/u.rao/.m2/repository/org/springframework/spring-webmvc/5.2.7.RELEASE/spring-webmvc-5.2.7.RELEASE.jar!/org/springframework/web/servlet/mvc/method/RequestMappingInfo.class

The class hierarchy was loaded from the following locations:

    org.springframework.web.servlet.mvc.method.RequestMappingInfo: file:/C:/Users/u.rao/.m2/repository/org/springframework/spring-webmvc/5.2.7.RELEASE/spring-webmvc-5.2.7.RELEASE.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.web.servlet.mvc.method.RequestMappingInfo

**Comment by raouday79** [comment]
after adding below
@Configuration
@ComponentScan("com.xss.filters")
public class Config {
}

**Comment by techguy-bhushan** [comment]
Hi @raouday79 , which version of spring boot are you working with for this?

**Comment by techguy-bhushan** [comment]
migrated application to spring-boot 3
